### PR TITLE
Smooth scrolling (initial push)

### LINKED ISSUE #3: Enable smooth scrolling!

### PR DESCRIPTION
**Pull request by k7kaushal**
I have implemented smooth scroll for 3 nav-links, let me know what changes are expected on top of this and I'll proceed accordingly. resolved #3

### CODE REVIEW

**Comment by theprinceraj** [comment]
Looking at the code, it seems it should be working fine. I will be merging the PR once I test it myself on my local machine. Thanks for the help to you @k7kaushal !

**Comment by theprinceraj** [comment]
Looking at the code, it seems it should be working fine. I will be merging the PR once I test it myself on my local machine. Thanks for the help to you!

However @k7kaushal , you didn't link this pull request to the respective issue. Please add #3 in your pull request description to link it with the issue.

**Comment by k7kaushal** [comment]
hi @theprinceraj , thank you for pointing it out, I have linked the issue to the PR, please check it out.
Please add hacktoberfest label after after review and merge of the PR.
It is a really great website! Liked to contribute.

**Comment by theprinceraj** [comment]
Thanks for this contribution! Merged it 👍🏻🤞

**Pull request merged**
